# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('national_initiatives', models.BooleanField(default=False)),
                ('sports_games', models.BooleanField(default=False)),
                ('cultural_activities', models.BooleanField(default=False)),
                ('professional_initiatives', models.BooleanField(default=False)),
                ('entrepreneurship_innovations', models.BooleanField(default=False)),
                ('leadership_management', models.BooleanField(default=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('proof', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
