# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_no', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=50)),
                ('class_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentauth.Classno')),
            ],
        ),
    ]
