# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
