# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentauth', '0002_auto_20171104_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='class_list',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Classno',
        ),
    ]
