# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentauth', '0004_auto_20171105_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
